### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by anjalsaneen** [zendesk/belvedere#107]
**Stacktrace:**
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.toString()' on a null object reference
>        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
>        at android.app.Activity.startActivityForResult(Activity.java:4396)
>        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
>        at android.app.Activity.startActivityForResult(Activity.java:4355)
>        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
>        at zendesk.belvedere.MediaIntent.open(MediaIntent.java:51)
>        at zendesk.belvedere.MediaIntent$DocumentIntentBuilder.open(MediaIntent.java:159)

**Belvedere Usage:**
```
Belvedere.from(context)
  .document()
  .contentType("image/*")
  .allowMultiple(false)
  .open((Activity) context);
```

**More Info**
84% - Crash from Xiaomi
Happening Across all the OS Version.

<img width="1537" alt="Screenshot 2020-01-19 at 4 37 51 PM" src="https://user-images.githubusercontent.com/43947967/72679957-95479780-3ada-11ea-9b94-619b6910d6db.png">

**Comment by Thamizhan** [comment]
Happening for us too. We are having different error

`
2021-10-05 18:44:33.430 10448-10448/com.shelfperks.android.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shelfperks.android.dev, PID: 10448
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
        at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:171)
        at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
        at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
        at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
        at com.shelfperks.android.views.fragments.HelpFragment.openGallery(SomeFragment.java:160)
        at com.shelfperks.android.views.fragments.HelpFragment.access$000(SomeFragment.java:55)
        at com.shelfperks.android.views.fragments.HelpFragment$2.onClick(SomeFragment.java:146)
        at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1250)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1187)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3179)
        at android.widget.AbsListView$3.run(AbsListView.java:4097)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
`

It seems the Intent from build method is returning null. 
We also tried to get the Intent from 
`belvedere.document().contentType("image/*").build().getIntent()`
