### ISSUE TITLE
Crash in ImageService 

### ISSUE THREAD

**Issue by sandeepvissamsetti-iconic** [zendesk/belvedere#126]
HI,

We have zendesk integrated in our app and it looks like we have crashes being reported to us. Please have a look at the stack trace and fix it if necessary. Let us know if there is anything on our side to modify. Using com.zendesk:chat:3.3.0 chat version and com.zendesk:messaging:5.2.0 messaging version. Here is the stacktrace,

ImageStreamService.java line 35
zendesk.belvedere.ImageStreamService.queryRecentImages(ImageStreamService.java:35)
zendesk.belvedere.ImageStreamModel.getLatestImages (ImageStreamModel.java:50)
zendesk.belvedere.ImageStreamPresenter.presentStream (ImageStreamPresenter.java:94)
zendesk.belvedere.ImageStreamPresenter.init (ImageStreamPresenter.java:25)
zendesk.belvedere.ImageStreamUi.<init> (ImageStreamUi.java:80)
zendesk.belvedere.ImageStreamUi.show (ImageStreamUi.java:45)
zendesk.belvedere.BelvedereUi$ImageStreamBuilder$1$1.run (BelvedereUi.java:199)

Let us know if you need anything else from our side.

**Comment by lelumees** [comment]
+1 seems to be an issue for me as well. Happens on Android 11 after application `targetSdkVersion` is bumped to 30.

**Comment by dat-vu-deca** [comment]
+1. Happens to our game when targetSdkVersion is changed to 30 as well.

**Comment by hiltonc** [comment]
This is the top crash in our app.

**Comment by cvance** [comment]
Same. Any update on this?

**Comment by cvance** [comment]
Adding stacktrace:

> Fatal Exception: java.lang.IllegalArgumentException: Invalid token LIMIT
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
       at android.content.ContentProviderProxy.query(ContentProviderProxy.java:473)
       at android.content.ContentResolver.query(ContentResolver.java:1194)
       at android.content.ContentResolver.query(ContentResolver.java:1125)
       at android.content.ContentResolver.query(ContentResolver.java:1081)
       at zendesk.belvedere.ImageStreamService.queryRecentImages(ImageStreamService.java:35)
       at zendesk.belvedere.ImageStreamModel.getLatestImages(ImageStreamModel.java:50)
       at zendesk.belvedere.ImageStreamPresenter.presentStream(ImageStreamPresenter.java:94)
       at zendesk.belvedere.ImageStreamPresenter.init(ImageStreamPresenter.java:25)
       at zendesk.belvedere.ImageStreamUi.<init>(ImageStreamUi.java:80)
       at zendesk.belvedere.ImageStreamUi.show(ImageStreamUi.java:45)
       at zendesk.belvedere.BelvedereUi$ImageStreamBuilder$1$1.run(BelvedereUi.java:199)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:254)
       at android.app.ActivityThread.main(ActivityThread.java:8231)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by dat-vu-deca** [comment]
Hi guys, after digging a while, I found solution for our project. Our project was using an old version of Belvedere. It is resolved by just updating Belvedere to newer version which include the fix. The fix can be found in this issue:
[](https://github.com/zendesk/belvedere/pull/111)
